### ISSUE TITLE
Readability/Accessibility Suggestions for Dark Mode

### ISSUE THREAD

**Issue by NovusOpus** [PaulineTW/portfolio#1]
**Hi Pauline, First of all, nice portfolio. I Like the clean, simple but also beautifully crafted design.** 

The reason of this issue is for sharing a suggestion. and also to share a few accessibility inconsistencies with your portfolio design. while in dark mode.

### 1. Add a Resume link for the Education/Work section in the navigation menu. 
You may also remove the home button link since it´s a Single page design and you have the Jump to Top Arrow when scrolling down, but on the other hand some people may find it useful for an extra easy access to get back to top, so it´s not redundant after all?)

---
### 2. Accessibility issue with the company name color in your work tab while on dark mode.
![Screenshot (798)](https://user-images.githubusercontent.com/79575415/172294076-50ca0d80-6154-4e70-97de-5a92b08059f7.png)
Currently there´s no color assigned for the company name link in dark mode, and have default blue link from the browser user agent stylesheet. And this is giving a warning in the Accessibility>Contrast checker in the Chrome DevTools as you can see in the next screenshot:

![Screenshot (802)](https://user-images.githubusercontent.com/79575415/172294319-15de0b72-8e01-44c8-b45d-7a3d6e2eb566.png)

You can fix this by setting the company name color in dark mode to your primary color: `color: var(--first-color);`
![Screenshot (805)](https://user-images.githubusercontent.com/79575415/172300568-3c104410-af04-4d6d-8a3f-57e7983e1c0f.png)
Changing the company name color in dark mode to your primary color CSS variable replaces the ⚠️ warning with a ✅ pass in the Chrome Dev Tools Accessibility>Contrast checker.

---

### 3. There's a glitch with your: Send message button in your Contact form.
![Screenshot (800)](https://user-images.githubusercontent.com/79575415/172296274-0e17d576-1355-4aee-896f-bcf0bd20d541.png)
The `button` element have no background color property defined, so it have the inherited button style: `background-color: buttonface;` (Whitish background) from the Browser Default User agent stylesheet, and combined with the rounded corner from the child `a` it looks glitchy in dark mode. You can fix this by also adding `border-radius: 0.5rem;` to the button element or setting a transparent background on it.

Just a few little details needing a fix while on dark mode, but again very nice work with your portfolio. 😄

**Comment by PaulineTW** [comment]
@NovusOpus, I have fixed the above issues. Thank you
